---
- name: Creates directory
  become: true
  file:
    path: '{{ item.dir }}'
    state: directory
    owner: '{{ item.owner }}'
    group: '{{ item.group }}'
  loop: '{{ scripts_dicts }}'

- name: Load scripts
  become: true
  template:
    src: "default_scripts.sh.j2"
    dest: '{{ item.dest }}'
    owner: '{{ item.owner }}'
    group: '{{ item.group }}'
    mode: '{{ item.mode }}'
  loop: '{{ scripts_dicts }}'

- name: Prepare cron
  template:
    src: "cron_cabo.j2"
    dest: '/etc/cron.d/cron_cabo'
