---
roles:
  # https://github.com/stefangweichinger/ansible-rclone
  - src: stefangweichinger.ansible_rclone
  # https://github.com/geerlingguy/ansible-role-nginx
  - src: geerlingguy.nginx
    version: 2.8.0
  # https://github.com/geerlingguy/ansible-role-pip
  - src: geerlingguy.pip
    version: 2.0.0
  # https://github.com/geerlingguy/ansible-role-certbot
  - src: geerlingguy.certbot
    version: 4.0.0
  # https://github.com/geerlingguy/ansible-role-postgresql
  - src: geerlingguy.postgresql
    version: 3.1.0
  # https://github.com/Oefenweb/ansible-fail2ban
  - src: oefenweb.fail2ban
    version: v3.4.1
  # https://github.com/geerlingguy/ansible-role-nfs
  - src: geerlingguy.nfs
    version: 2.0.0


collections:
  - name: ansible.posix
  - name: community.general
  - name: community.postgresql
