---
- name: Install VM NAS
  hosts: cabo200
  become: true
  gather_facts: true

  vars_files:
    - ../cabo200_variables.yml

  roles:
    - role: nfs-volume
    - role: nfs-server
    - role: geerlingguy.nfs
