---
- name: Install Python 2
  hosts: cabo002
  become: true
  
  roles:
    - nfs_client
    - stefangweichinger.ansible_rclone
    - fulcrum-post-processing
    - fulcrum-webhook
    - fulcrum-scripts
