---
- name: Install Python 2
  hosts: cabo002
  become: true
  
  roles:
    - nfs_client
    - backup-google-drive
    - backup-fulcrum
    - fulcrum-post-processing
    - fulcrum-webhook
    - fulcrum-scripts
    - fulcrum-cron
