---
- name: Install VM web
  hosts: cabo100
  become: true

  vars_files:
    - ../cabo100_variables.yml

  pre_tasks:
    - name: Install crontab
      apt:
        pkg   : rsync
        state : latest

  roles:
    - nfs-client
    - static-web
    - geerlingguy.nginx
    - geerlingguy.certbot
    - data-web
    - cabo-api
    - cabo-vis
    #- fail2ban
    #- fail2ban_nginx
