---
# directories
gunicorn_version: "20.0.4"
flask_version   : "1.1.2"

pip_install_packages:
  - name: virtualenv
  - name: gunicorn
    version: '{{ gunicorn_version }}'
  - name: Flask
    version: '{{ flask_version }}'

webhook_directory: '/home/{{ ansible_ssh_user }}/{{ app_name }}'
webhook_app_directory: '/home/{{ ansible_ssh_user }}/{{ app_name }}'
webhook_data_directory: '/home/{{ ansible_ssh_user }}/{{ app_name }}'
webhook_env_directory: '/home/{{ ansible_ssh_user }}/{{ app_name }}'
webhook_bind: '127.0.0.1:80'
webhook_workers: 1

app_name: hello
app_name_content: "Hello world"
