---
# directories
app_name=hello
webhook_directory: '/home/{{ ansible_ssh_user }}/{{ app_name }}'

gunicorn_version: "20.0.4"
flask_version   : "1.1.2"

pip_install_packages:
  - name: gunicorn
    version: '{{ gunicorn_version }}'
  - name: Flask
    version: '{{ flask_version }}'

