---
- name: Copy application files
  ansible.builtin.file:
    path: '{{ webhook_app_directory }}/.env'
    state: directory
    mode: '0755'

- name: Load wsgi.py
  ansible.builtin.template:
    src: wsgi.py.j2
    dest: '{{ webhook_app_directory }}/wsgi.py'

- name: Load App
  ansible.builtin.template:
    src: app_name.py.j2
    dest: '{{ webhook_app_directory }}/{{ app_name }}.py'

- name: Load Webhook requirements
  ansible.builtin.template:
    src: requirements.j2
    dest: '{{ webhook_app_directory }}/requirements.txt'

- name: Install modules in a virtualenv
  pip:
    requirements: '{{ webhook_app_directory }}/requirements.txt'
    virtualenv: '{{ webhook_env_directory }}'

- name: Load Service template
  become: yes
  ansible.builtin.template:
    src: webhook_service.j2
    dest: '/etc/systemd/system/{{ app_name }}.service'

- name: Reload Deamon
  ansible.builtin.systemd:
    daemon_reload: yes

- name: 'Enable and Start {{ app_name }} service'
  become: yes
  systemd:
    name: '{{ app_name }}.service'
    state: restarted
    enabled: yes

- name: Recursively change ownership of a directory
  ansible.builtin.file:
    path: '{{ webhook_app_directory }}'
    state: directory
    recurse: yes
    owner: '{{ default_user }}'
    group: '{{ default_grp }}'
