---
- name: Update apt cache
  apt:
    pkg   : git
    state : latest
    update_cache: yes
 
- name: Download fulcrum post processing from github
  ansible.builtin.git:
    repo  : https://github.com/CABOscience/fulcrum_post_processing.git
    dest  : '{{ fpp_directory }}'
    force : yes

- name: Prepare config
  template:
    src: "config.ini.j2"
    dest: '{{ fpp_directory }}/config.ini'

- name: Prepare directory for modules
  ansible.builtin.file:
    path: '{{ fpp_modules_directory }}'
    state: '{{ item }}'
  loop:
    - absent
    - directory

- name: Download Specdal from github
  ansible.builtin.git:
    repo  : '{{ item.git }}'
    dest  : '{{ fpp_modules_directory }}/{{ item.name }}'
    version: '{{ item.version }}'
    force : yes
  loop: '{{ fpp_modules }}'

- name: Install specdal module
  ansible.builtin.shell:
    cmd: python3 setup.py install
    chdir: '{{ fpp_modules_directory }}/{{ item.name }}'
  loop: '{{ fpp_modules }}'

- name: Recursively change ownership of '{{ fpp_directory }}'
  ansible.builtin.file:
    path: '{{ fpp_directory }}'
    state: directory
    recurse: yes
    owner: '{{ default_user }}'
    group: '{{ default_user }}'
