---
- name: Install UFW packages
  apt:
    pkg             : 'ufw'
    state           : present
    update_cache    : yes
    cache_valid_time: '{{ apt_cache_valid_time }}'
    
- name: ufw - Setup ufw
  community.general.ufw:
    state   : enabled
    policy  : deny

- name: ufw - Allow traffics
  community.general.ufw:
    rule    : allow
    port    : '{{ item }}'
    proto   : tcp
  with_items: "{{ ufw_ports }}"

- name: Ensure ufw starts on a fresh reboot
  ansible.builtin.service:
    name    : ufw
    state   : restarted
    enabled : yes
