---
- name: Install packages nodejs and npm
  ansible.builtin.apt:
    pkg:
      - nodejs
      - npm
    state: latest

- name: npm install dependencies
  community.general.npm:
    name: '{{ item.name }}'
    version: '{{ item.version }}'
    global: yes
  loop: '{{ npm_dict }}'

- name: Init pm2
  shell:
    cmd: pm2 init
