---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: '{{ apt_cache_valid_time }}'
  register: update_action
 
- name: Upgrade APT to the latest packages
  apt:
    upgrade: safe
  when: update_action.changed

- name: Install Common packages ubuntu 20.04
  apt:
    pkg: '{{ commom_pkgs_2004 }}'
    state: latest
