---
- name: Install git
  apt:
    pkg   : git
    state : latest
    update_cache: yes

- name: Create directory for static
  ansible.builtin.file:
    path: '{{ web_static_directory }}'
    state: absent

- name: Download Static pages from github
  ansible.builtin.git:
    repo  : '{{ web_static_github_link }}'
    dest  : '{{ web_static_directory }}'
    force : yes

- name: Clean from github
  ansible.builtin.file:
    dest  : '{{ web_static_directory }}/{{ item }}'
    state : absent
  loop:
    - "LICENSE"
    - "README.md"
    - ".git"

#
# Not sure about that part
#
#- name: Change the chmod file
#  file:
#    dest    : '{{ web_static_directory }}'
#    mode    : u=rwX,g=rX,o=rX
#    recurse : yes


